import { makeStyles } from '@material-ui/core/styles';

const useStyles = makeStyles(() => ({
  dialogContent: { height: 478 },
  root: {
    height: '100%',
    alignContent: 'space-evenly',
  },
  label: {
    color: '#485563',
    fontSize: 16,
    fontWeight: 'bold',
    right: '5%',
    position: 'relative',
    paddingBottom: '1%',
  },
  circular: {
    width: '148px',
    textAlign: 'center',
  },
  confirm: {
    fontSize: 14,
    borderRadius: 10,
    backgroundColor: '#2B64E9',
    color: 'white',
    width: '148px',
    '&:hover': { backgroundColor: '#2B64E9' },
    right: '35%',
  },
  cancel: {
    fontSize: 14,
    color: '#8E8E93',
    boxSizing: 'borderBox',
    border: '1px solid #BDBDBD',
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    width: '148px',
    right: '35%',
  },
  error: {
    color: 'red',
    fontSize: 13,
  },
  uniteList: {
    width: '100%',
    height: '170px',
    'overflow-x': 'hidden',
    'margin-bottom': '2%',
    'padding-right': '6px',
  },
  uniteListItem: { 'margin-bottom': '2%' },
  deleteEquipButton: {
    borderRadius: '2px',
    fontSize: '12px',
    fontWeight: '500',
    backgroundColor: 'transparent',
    color: '#464d5a',
    border: 'none',
    textTransform: 'none',
    marginRight: '10px',
    '&:hover': {
      color: '#ffffff',
      backgroundColor: 'transparent',
    },
    left: '62%',
  },
  deleteButtonIcon: { fontSize: '20px' },
  addEquipButton: {
    height: '38px',
    width: '189px',
    fontFamily: 'Roboto',
    boxShadow: '0 0px 0px 0px #1974fe',
    'background-color': '#1974fe',
    textAlign: 'left',
    borderRadius: '32px',
    '&:hover': { 'background-color': '#1974fe' },
    position: 'absolute',
    left: '82%',
    top: '10%',
    cursor: 'pointer',
    borderStyle: 'hidden',
    zIndex: '1000',
  },
  buttonEquipTxt: {
    fontFamily: 'Roboto',
    fontSize: '14px',
    fontWeight: 'bold',
    textAlign: 'center',
    color: 'white',
    lineHeight: 'normal',
    textTransform: 'none',
    padding: '0 16px',
  },
  addCheckPointButton: {
    top: '19%',
    width: '162px',
    cursor: 'pointer',
    height: '32px',
    boxShadow: '0 0px 0px 0px #1974fe',
    textAlign: 'left',
    fontFamily: 'Roboto',
    borderStyle: 'hidden',
    borderRadius: '32px',
    backgroundColor: '#34cf13cc',
    marginTop: '7px',
    marginBottom: '5px',
  },
  buttonCheckPointTxt: {
    fontFamily: 'Roboto',
    fontSize: '14px',
    fontWeight: 'bold',
    textAlign: 'center',
    color: 'white',
    lineHeight: 'normal',
    textTransform: 'none',
  },
  addCritereButton: {
    top: '5%',
    position: 'relative',
    left: '4%',
    width: '122px',
    cursor: 'pointer',
    height: '29px',
    boxShadow: '0 0px 0px 0px #1974fe',
    textAlign: 'left',
    fontFamily: 'Roboto',
    borderStyle: 'hidden',
    borderRadius: '32px',
    backgroundColor: '#06276a9e',
    marginTop: '7px',
  },
  buttonCritereTxt: {
    fontFamily: 'Roboto',
    fontSize: '14px',
    fontWeight: 'bold',
    textAlign: 'center',
    color: 'white',
    lineHeight: 'normal',
    textTransform: 'none',
  },
  deleteCheckPointButton: {
    borderRadius: '2px',
    fontSize: '12px',
    fontWeight: '500',
    backgroundColor: 'transparent',
    color: '#464d5a',
    border: 'none',
    textTransform: 'none',
    marginRight: '10px',
    '&:hover': {
      color: '#ffffff',
      backgroundColor: 'transparent',
    },
    left: '53%',
  },
  deleteCritereButton: {
    borderRadius: '2px',
    fontSize: '12px',
    fontWeight: '500',
    backgroundColor: 'transparent',
    color: '#464d5a',
    border: 'none',
    textTransform: 'none',
    marginRight: '10px',
    '&:hover': {
      color: '#ffffff',
      backgroundColor: 'transparent',
    },
    left: '0%',
  },
  fab: {
    backgroundColor: '#efefef',
    boxShadow: 'none',
    width: '65px',
    height: '65px',
    display: 'inline',
    textTransform: 'capitalize',
    fontSize: '12px',
    color: '#C5CBDB',
    fontFamily: 'Roboto',
    lineHeight: '19px',
    '&:hover': {
      color: '#8092A5',
      backgroundColor: '#efefef',
    },
    marginLeft: '18px',
    marginRight: '18px',
    position: 'absolute',
    top: '10px',
  },
  icon: {
    color: '#8092A5',
    width: '30%',
    height: '30%',
  },
}));

export default useStyles;
